version: "3.8"

services:
  localstack:
    container_name: "localstack_compose"
    image: localstack/localstack
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4599:4510-4599"
    environment:
      - SERVICES=sqs,sns,s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - HOSTNAME_EXTERNAL=localstack

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - localstack_network
networks:
  localstack_network: